name : PR Tester Action

on : [ push, pull_request ]

jobs :
  build :
    # Only run on PRs if the source branch is on someone else's repo
    if : ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - uses : gradle/wrapper-validation-action@v1
      - name : Cache Gradle
        uses : actions/cache@v2.1.3
        with :
          path : ~/.gradle/caches
          key : ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-ssp

      - name : Set up JDK 8
        uses : actions/setup-java@v1
        with :
          java-version : 8

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Test with Gradle
        run : ./gradlew build test

      - uses : actions/upload-artifact@v2
        with :
          path : build/libs/SuperSolarPanels*
          if-no-files-found : error
